semantic_scene_completion:
    source: 
        local:
            root: ${oc.env:EFG_PATH}/datasets/semantic_kitti
            data: dataset/sequences
            label: dataset/labels 
            msnet3d_data: dataset/sequences_msnet3d_sweep10
            splits:
                train: ["00", "01", "02", "03", "04", "05", "06", "07", "09", "10"]
                val: ["08"]
                test: ["11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21"]




